baseURL: "http://example.org/"
languageCode: "en-gb"
title: "dan.dev"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: dan.dev
  description: "Dan's blog"
  author: dan

  defaultTheme: dark
  disableThemeToggle: true
  ShowPostNavLinks: true
  ShowReadingTime: true
  ShowShareButtons: false
  disableSpecial1stPost: false
  comments: false
  hidemeta: false
  showtoc: false
  tocopen: false
  menu:
    main:
      - identifier: categories
        name: categories
        url: /categories/
        weight: 10
      - identifier: tags
        name: tags
        url: /tags/
        weight: 20
      - identifier: example
        name: example.org
        url: https://example.org
        weight: 30
